#: kivy 1.0.9

<SaunaDisplay>
    canvas:
        Rectangle:
            pos: 0,0
            size: 5, self.height
        
        Rectangle:
            pos: 0,0
            size: self.width, 5

        Rectangle:
            pos: self.width - 5, 0
            size: 5, self.height
        
        Rectangle:
            pos: 0, self.height - 5
            size: self.width, 5
    
    Label:
        font_size: 50
        center: self.parent.center
        text: "test"
